spring.application.name=hubeducativocolombia
spring.datasource.url=jdbc:mysql://localhost:3306/db_hubeducativocolombia
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
